#!/root/miniconda3/envs/genesis/bin/python

import argparse

parser = argparse.ArgumentParser('description=File to read')
parser.add_argument('filename', help='file to read' )
parser.add_argument('--limit', '-l', type=int, help='limit files read' )
parser.add_argument('--version', '-v', action='version', version='%(prog)s 1.0' )


args = parser.parse_args()
#print (args)

try:
  f = open(args.filename)
  limit = args.limit
#except FileNotFoundError as err:
 # print(f"Error: {err}")
except:
  print(f"Testing ")
else:
  with f:
    lines = f.readlines()
    lines.reverse()


    if args.limit:
      lines = lines[:limit]

    for lines in lines:
      print(lines.strip()[::-1])

finally:
  print("Finally")
#with open(args.Filename) as f:
#  lines = f.readlines()
#  lines.reverse()


#  if args.limit:
#    lines = lines[:args.limit]

#  for lines in lines:
#    print(lines.strip()[::-1])
